_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
dataset:
    value: EmnistDataset
experiment_group:
    value: Sample Experiments 2
gpu_ind:
    value:
        - 0
model:
    value: CharacterModel
network:
    value: mlp
network_args:
    value:
        num_layers: 2
train_args:
    value:
        batch_size: 256
        epochs: 16
